sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-411069203272"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY