sudo: required
services:
  - docker

before_install:
  - docker build -t ifeanyilawrence/docker-react -f Dockerfile.dev .

script:
  - docker run -t ifeanyilawrence/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-411069203272"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: AKIAV7NNCINEEERS7Q2L
  secret_access_key: 
    secure: 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