sudo: required
services:
  - docker

before_install:
  - docker build -t ifeanyilawrence/docker-react -f Dockerfile.dev .

script:
  - docker run -t ifeanyilawrence/docker-react yarn test -- --coverage